name: Test Email Step

on:
  workflow_dispatch:  # Allows manual trigger from Actions tab

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 24f2000817@ds.study.iitm.ac.in
        run: echo "Hello, world!"
